import {TableListItem} from "@/beans/system";

export type DemandStatus = 'PENDING' | 'PUBLISHED' | 'COMPLETED' | 'SETTLED' | 'CLOSED';

/** 分账单(后端 DemandView.settlement)。金额单位:元。 */
export interface DemandSettlement {
  demandId: number;
  /** 付给认领人的赏金合计 */
  totalPay: number;
  /** 退回发布者的未分配赏金 */
  refundPay?: number;
  approvedCount: number;
  distribution: Array<{
    assigneeId: number;
    assigneeName: string;
    taskCount: number;
    amount: number;
  }>;
  completedAt?: string | null;
  settledAt?: string | null;
  /** true = 尚未结账,是按当前验收结果算出的预估 */
  preview?: boolean;
}

export interface DemandItem extends TableListItem {
  /** 发布在哪个意境(topic)里,0 = 不属于任何意境 */
  topicId?: number;
  title?: string;
  tags?: any;
  subtitle?: string;
  content?: any;
  cover?: string;
  pay?: number;
  category?: string;
  status?: DemandStatus | string;
  realizations?: any;
  myRealizations?: any;
  publishTime?: string;
  endTime?: string;
  username?: string;
  avatar?: string;
  /** 发布者是平台运营的 AI 用户 */
  isBot?: boolean;
  taskIds?: number[];
  /** 验收通过的任务数 */
  completedCount?: number;
  totalTaskCount?: number;
  /** 还没人认领的任务数 */
  openTaskCount?: number;
  /** 认领过任务的人数 */
  applicants?: number;
  /** 发布时从钱包托管、尚未发出的赏金(分) */
  escrowCents?: number;
  settledAt?: string | null;
  settlement?: DemandSettlement | null;
}

export interface GroupItem extends TableListItem {
  name?: string;
  info?: string;
  content?: string;
  projects?: number;
  url?: string;
  cover?: string;
  status?: string;
  username?: string;
}

export interface ProjectItem extends TableListItem {
  name?: string;
  cover?: string;
  groups?: number
  content?: string;
  url?: string;
  logo?: string;
  status?: string;
  username?: string;
  avatar?: string;
  info?: string;
  tags?: any;
  category?: string;
}

export interface RealizationItem extends TableListItem {
  title?: string;
  subtitle?: string;
  content?: any;
  cover?: string;
  status?: string;
  publishTime?: string;
  endTime?: string;
  username?: string;
  avatar?: string;
  demands?: any;
  demandId?: number;
  taskId?: number;
  userId?: number;
  autoGenerated?: boolean;
}

export interface ConceptionItem extends TableListItem {
  name?: string;
  info?: string;
  content?: string;
  cover?: string;
  date?: string;
  pay?: number;
  status?: string;
  username?: string;
  avatar?: string;
  tags?: string;
  category?: string;
  demandId?: number;
}

export type RewardTaskStatus = 'OPEN' | 'CLAIMED' | 'SUBMITTED' | 'APPROVED' | 'REJECTED';
export type TaskPriority = 'P0' | 'P1' | 'P2';

export interface RewardTask extends TableListItem {
  /** 认领它的团队,0 / 空 = 个人认领 */
  teamId?: number;
  /** 团队任务里实际提交交付的那位成员 */
  submitterId?: number;
  demandId?: number | null;
  title?: string;
  description?: string;
  assigneeId?: number | null;
  assigneeName?: string;
  assigneeAvatar?: string;
  /** 认领人是平台运营的 AI 用户(交付由 AI 生成) */
  assigneeIsBot?: boolean;
  status?: RewardTaskStatus;
  priority?: TaskPriority;
  deadline?: string | null;
  deliverable?: string | null;
  reviewNote?: string | null;
  createdBy?: number;
  createdAt?: string;
  updatedAt?: string;
  claimedAt?: string | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  /** 任务标价(元);0 表示与其他未标价任务均分需求剩余赏金 */
  reward?: number;
  /** 是否公开(供公开任务池展示)。true/缺省 = 公开。 */
  isPublic?: boolean;
  /** 有权编辑、验收此任务的用户:需求发布者,或独立任务的负责人 */
  managerId?: number;
  demandTitle?: string;
  demandStatus?: string;
  /** 发布者是平台运营的 AI 用户 */
  managerIsBot?: boolean;
  /** 最近一次平台仲裁的状态;没申请过为空 */
  disputeStatus?: 'pending' | 'resolved' | 'rejected';
  /** 交付的作品(我的作品里的一件)及提交时的快照;BIGINT 按字符串下发 */
  workId?: string | number;
  workType?: string;
  workTitle?: string;
  workCover?: string;
}
