import {TableListItem} from "@/beans/system";

export type DemandStatus = 'PENDING' | 'PUBLISHED' | 'COMPLETED' | 'SETTLED' | 'CLOSED';

export interface DemandSettlement {
  demandId: number;
  totalPay: number;
  approvedCount: number;
  distribution: Array<{
    assigneeId: number;
    assigneeName: string;
    taskCount: number;
    amount: number;
  }>;
  completedAt: string;
  settledAt: string;
}

export interface DemandItem extends TableListItem {
  title?: string;
  tags?: any;
  subtitle?: string;
  content?: any;
  cover?: string;
  pay?: number;
  status?: DemandStatus | string;
  realizations?: any;
  myRealizations?: any;
  publishTime?: string;
  endTime?: string;
  username?: string;
  avatar?: string;
  taskIds?: number[];
  completedCount?: number;
  totalTaskCount?: number;
  settledAt?: string | null;
  settlement?: DemandSettlement | null;
}

export interface GroupItem extends TableListItem {
  name?: string;
  info?: string;
  content?: string;
  projects?: number;
  url?: string;
  cover?: string;
  status?: string;
  username?: string;
}

export interface ProjectItem extends TableListItem {
  name?: string;
  cover?: string;
  groups?: number
  content?: string;
  url?: string;
  logo?: string;
  status?: string;
  username?: string;
  avatar?: string;
  info?: string;
  tags?: any;
  category?: string;
}

export interface RealizationItem extends TableListItem {
  title?: string;
  subtitle?: string;
  content?: any;
  cover?: string;
  status?: string;
  publishTime?: string;
  endTime?: string;
  username?: string;
  avatar?: string;
  demands?: any;
  demandId?: number;
  taskId?: number;
  userId?: number;
  autoGenerated?: boolean;
}

export interface ConceptionItem extends TableListItem {
  name?: string;
  info?: string;
  content?: string;
  cover?: string;
  date?: string;
  pay?: number;
  status?: string;
  username?: string;
  avatar?: string;
  tags?: string;
  category?: string;
  demandId?: number;
}

export type RewardTaskStatus = 'OPEN' | 'CLAIMED' | 'SUBMITTED' | 'APPROVED' | 'REJECTED';
export type TaskPriority = 'P0' | 'P1' | 'P2';

export interface RewardTask extends TableListItem {
  projectId?: number;
  groupId?: number;
  groupIds?: number[];
  demandId?: number | null;
  title?: string;
  description?: string;
  assigneeId?: number | null;
  assigneeName?: string;
  assigneeAvatar?: string;
  status?: RewardTaskStatus;
  priority?: TaskPriority;
  deadline?: string | null;
  deliverable?: string | null;
  reviewNote?: string | null;
  createdBy?: number;
  createdAt?: string;
  updatedAt?: string;
  claimedAt?: string | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
}
